# Register User
POST http://localhost:4001/api/users/register
Content-Type: application/json

{
    "username": "testuser",
    "password": "testpassword"
}

### 

# Login User
POST http://localhost:4001/api/users/login
Content-Type: application/json

{
    "username": "testuser",
    "password": "testpassword"
}
